"""
Workflow Constants and Configuration Values
All hardcoded values from the LangGraph workflow system
"""

# Default values for GraphState
DEFAULT_MAX_ITERATIONS = 50
DEFAULT_TARGET_CHAPTERS = 10
DEFAULT_CONTENT_SNIPPET_LIMIT = 500
DEFAULT_MIN_CONTENT_THRESHOLD = 50
DEFAULT_CHAPTER_NORMALIZATION_FACTOR = 5000
DEFAULT_CHAPTER_COMPLETION_THRESHOLD = 0.9
DEFAULT_MICRO_COMPLETION_FACTOR = 0.9
DEFAULT_PROGRESS_INCREMENT_MACRO = 0.3
DEFAULT_PROGRESS_INCREMENT_WORLD = 0.2
DEFAULT_PROGRESS_INCREMENT_CHARACTERS = 0.2
DEFAULT_PROGRESS_INCREMENT_ARC = 0.3

# Loop prevention constants
LOOP_DETECTION_THRESHOLD = 10
INFINITE_LOOP_SAFETY_FACTOR = 5
MAX_RELATED_NODES_SEQUENCE = 5

# Phase transition thresholds
MACRO_COMPLETION_CHAPTERS_COUNT = 3
MACRO_MIN_CHARACTER_COUNT = 2
MACRO_MIN_WORLD_DETAILS_COUNT = 3
PROGRESS_THRESHOLD_FOR_TRANSITION = 0.8

# Content quality thresholds
MIN_OUTLINE_LENGTH = 1
MIN_WORLD_BUILDING_THRESHOLD = 3
CHAPTER_LENGTH_NORMALIZATION_FACTOR = 5000

# Agent-specific limits
AGENT_RESPONSE_SNIPPET_LIMIT = 500
PACING_ADVISOR_EXCERPT_LIMIT = 500

# Phase progress calculation multipliers
MACRO_OUTLINE_PROGRESS_MULTIPLIER = 0.3
MACRO_WORLD_PROGRESS_MULTIPLIER = 0.2
MACRO_CHARACTERS_PROGRESS_MULTIPLIER = 0.2
MACRO_ARC_PROGRESS_MULTIPLIER = 0.3

# Node routing thresholds
DEFAULT_CHAPTER_SIZE_THRESHOLD = 100
COMPLETED_CHAPTERS_PROGRESSION_RATIO = 0.9
CONTENT_THRESHOLD_SHORT = 50

# Phase transition rules
MIN_STORY_OUTLINE_CHAPTERS = 1
MAX_CHAPTERS_TARGET_DEFAULT = 10
TARGET_MID_COMPLETION_DEFAULT = 10

# Error and retry configuration
DEFAULT_MAX_ERRORS = 5
DEFAULT_ITERATION_RETRY_ATTEMPTS = 3
PREFETCH_CACHE_SIZE = 1000

# Phase completion thresholds
MACRO_PHASE_COMPLETION_THRESHOLD = 0.8
MID_PHASE_COMPLETION_THRESHOLD = 0.9
MICRO_PHASE_COMPLETION_THRESHOLD = 1.0

# Chapter planning thresholds
CHAPTER_CONTENT_LENGTH_NORMALIZATION = 5000
MIN_CHAPTER_WORDS_FOR_COMPLETION = 100

# Agent phase mapping thresholds
WORLD_BUILDER_PHASE_THRESHOLD = 3  # Min world details needed
CHARACTER_DEVELOPMENT_THRESHOLD = 2  # Min characters needed
STORY_OUTLINE_CHAPTERS_THRESHOLD = 3  # Min outline chapters needed

# Cycle protection parameters
MAX_ITERATIONS_PER_NODE = 5
NODE_EXECUTION_SEQUENCE_LIMIT = 10